---

- name: stop dockerized PSQL containers
  become: yes
  command: docker-compose down
  args:
    chdir: "/opt/uptycs/etc/postgres/{{ item }}"
  with_items:
    - configdb
    - metastoredb
    - statedb

- name: Create BaseBackup & wal_files_archive directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ replication_user }}"
    group: "{{ replication_user }}"
    recurse: yes
  with_items:
    - '{{ backup_path }}'

- name: Backup postgresql.conf 
  become: yes
  copy:
    src: "/opt/uptycs/etc/postgres/{{ item }}/postgresql.conf"
    dest: "/opt/uptycs/etc/postgres/{{ item }}/postgresql.conf-original"
    remote_src: yes
  with_items:
    - configdb
    - metastoredb
    - statedb


- name: Add PG Backup settings to configdb/postgresql.conf
  become: yes
  lineinfile:
    dest: "/opt/uptycs/etc/postgres/configdb/postgresql.conf"
    insertafter: EOF
    line: "{{ item }}"
    state: present
  with_items:
    - "#=== ENABLE WAL ARCHIVING ==="
    - archive_mode = on
    - wal_level = logical
    - "archive_command = 'test ! -f {{ backup_path }}configdb/walfiles_archive/%f && cp %p {{ backup_path }}configdb/walfiles_archive/%f'"


- name: Add PG Backup settings to metastoredb/postgresql.conf
  become: yes
  lineinfile:
    dest: "/opt/uptycs/etc/postgres/metastoredb/postgresql.conf"
    insertafter: EOF
    line: "{{ item }}"
    state: present
  with_items:
    - "#=== ENABLE WAL ARCHIVING ==="
    - archive_mode = on
    - wal_level = logical
    - "archive_command = 'test ! -f {{ backup_path }}metastoredb/walfiles_archive/%f && cp %p {{ backup_path }}metastoredb/walfiles_archive/%f'"

- name: Add PG Backup settings to statedb/postgresql.conf
  become: yes
  lineinfile:
    dest: "/opt/uptycs/etc/postgres/statedb/postgresql.conf"
    insertafter: EOF
    line: "{{ item }}"
    state: present
  with_items:
    - "#=== ENABLE WAL ARCHIVING ==="
    - archive_mode = on
    - wal_level = logical
    - "archive_command = 'test ! -f {{ backup_path }}statedb/walfiles_archive/%f && cp %p {{ backup_path }}statedb/walfiles_archive/%f'"



- name: Add replication user to configdb/pg_hba.conf
  become: yes
  lineinfile:
    dest: "/opt/uptycs/etc/postgres/configdb/pg_hba.conf"
    insertafter: EOF
    line: "{{ item }}"
    state: present
  with_items:
    - 'host  replication {{ replication_user }}  127.0.0.1/32    md5'

- name: Add replication user to metastoredb/pg_hba.conf
  become: yes
  lineinfile:
    dest: "/opt/uptycs/etc/postgres/metastoredb/pg_hba.conf"
    insertafter: EOF
    line: "{{ item }}"
    state: present
  with_items:
    - 'host  replication {{ replication_user }}  127.0.0.1/32    md5'


- name: Add replication user to statedb/pg_hba.conf
  become: yes
  lineinfile:
    dest: "/opt/uptycs/etc/postgres/statedb/pg_hba.conf"
    insertafter: EOF
    line: "{{ item }}"
    state: present
  with_items:
    - 'host  replication {{ replication_user }}  127.0.0.1/32    md5'


# - name: Backup docker-compose.yml

# - name: Generate docker-compose.yml with backup Volumes

- name: start dockerized PSQL containers
  become: yes
  command: docker-compose up -d
  args:
    chdir: "/opt/uptycs/etc/postgres/{{ item }}"
  with_items:
    - configdb
    - metastoredb
    - statedb


- name: Check status of Databases
  postgresql_ping:
    db: "{{ item.key }}"
    login_host: localhost
    port: "{{ item.value }}"
    login_user: "{{ replication_user }}"
    login_password: "{{ replication_user_pw }}"
  loop: "{{ db_port | dict2items }}"
  vars:
    db_port:
      configdb: 5432
      metastoredb: 5433
      statedb: 5434


- name: Force PostgreSQL to switch to a new WAL file
  postgresql_query:
    login_host: localhost
    port: "{{ item }}"
    login_user: '{{ replication_user }}'
    login_password: '{{ replication_user_pw }}'
    query: SELECT pg_switch_wal();
  with_items:
    - 5432
    - 5433
    - 5434


# - name: Check wal_files_archive to confirm new WAL is generated

- name: Take Initial PG_BASEBACKUP of ConfigDB
  become: yes
  shell: >
     export PGPASSWORD="{{ replication_user_pw }}" && pg_basebackup -h localhost -p 5432 
     -U postgres -D "{{ backup_path }}"/configdb/basebackup/
     --tablespace-mapping=/data/pgdata/configdb="{{ backup_path }}"/configdb/0-pg_tblspc-24576-backup
     --waldir="{{ backup_path }}"/configdb/base-pg_wal-backup -P -v >> /tmp/base-backup.log 2>&1


- name: Take Initial PG_BASEBACKUP of MetastoreDB
  become: yes
  shell: >
     export PGPASSWORD="{{ replication_user_pw }}" && pg_basebackup -h localhost -p 5433
     -U postgres -D "{{ backup_path }}"/metastoredb/basebackup/
     --tablespace-mapping=/data/pgdata/metastoredb="{{ backup_path }}"/metastoredb/0-pg_tblspc-24576-backup
     --waldir="{{ backup_path }}"/metastoredb/base-pg_wal-backup -P -v >> /tmp/base-backup.log 2>&1


- name: Take Initial PG_BASEBACKUP of StateDB
  become: yes
  shell: >
     export PGPASSWORD="{{ replication_user_pw }}" && pg_basebackup -h localhost -p 5434 
     -U postgres -D "{{ backup_path }}"/statedb/basebackup/
     --tablespace-mapping=/data/pgdata/statedb="{{ backup_path }}"/statedb/0-pg_tblspc-24576-backup
     --waldir="{{ backup_path }}"/statedb/base-pg_wal-backup -P -v >> /tmp/base-backup.log 2>&1


- name: Sync Initial PG_BASEBACKUP & WAL archives to S3 
  become: yes
  shell: aws s3 sync "{{ backup_path }}" "{{ s3_db_backup_url }}"

- name: Add crontab for s3 sync
  cron:
    name: "Sync DB-Backup to s3"
    minute: "0"
    hour: "12"
    user: ubuntu
    job: aws s3 sync "{{ backup_path }}" "{{ s3_db_backup_url }}"
    cron_file: db-back-s3sync

- name: Add crontab for periodic BaseBackup
  cron:
    name: "Create New BaseBackup"
    minute: "0"
    hour: "12"
    user: ubuntu
    job: echo "test periodic task" > /tmp/test-periodic-task.txt
    cron_file: db-back-s3sync
