---

- name: TEST
  gather_facts: false
  become: yes
  hosts: all
  vars:
    - backup_path: /warehouse/db-backup
    - configdb_wal_archive: /warehouse/db-backup/configdb/walfiles
    - metastoredb_wal_archive: /warehouse/db-backup/metastoredb/walfiles
    - statedb_wal_archive: /warehouse/db-backup/statedb/walfiles
    - conf_path: /opt/uptycs/etc/postgres
    - replication_user: postgres
    - replication_user_pw: pguptycs
    - uptycs_service_user: monkey
    - s3_db_backup_url: s3://apj-db-backup
    - basebackup_log: /tmp/basebackup.log

  tasks:
    - name: Create Symlinks for walfiles-archive directories
      become: yes
      file:
        src: "{{ item.key }}"
        dest: "{{ item.value }}"
        state: link
        owner: "{{ uptycs_service_user }}"
        group: "{{ uptycs_service_user }}"
      loop: "{{ symlinks | dict2items }}"
      vars:
        symlinks:
          /pg/configdb/backup/walfiles_archive: "{{ backup_path }}/configdb/walfiles_archive"
          /pg/metastoredb/backup/walfiles_archive: "{{ backup_path }}/metastoredb/walfiles_archive"
          /pg/statedb/backup/walfiles_archive: "{{ backup_path }}/statedb/walfiles_archive"


